name: update
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit files
        run: |
          git clone ${{ secrets.PROJECT_SOURCE_GIT_URL }} source
          git clone ${{ secrets.PROJECT_TARGET_GIT_URL }} target
      
      - name: Setup .NET Core SDK      
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.0
        
      - name: Execute Update
        run: |
          dotnet run --project source 
          cd target
          git config --local user.email "m67186636@gmail.com"
          git config --local user.name "m67186636"
          git commit -a -m "Add changes"          

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
